# W200 Introduction to Data Science Programming, UC Berkeley MIDS
# Project 2

The final project will comprise an Exploratory Data Analysis of a dataset of your choosing using the numpy and pandas tools.

- Push your proposal to your team's GitHub repository and update the link in gradescope by 11:59PM PST the day before class, **week 12** 
- Your group will give a 10 minute presentation during your final class, **week 14**
- Push your report to your team's GitHub repository and update the link in gradescope by 11:59PM PST the day **after** class, **week 14**.

Some past showcase projects are here: https://github.com/UCB-INFO-PYTHON/Project2_Showcase

## Instructions

#### Team
- Form a team of 2 to 3 students. By exception, a team of 4 students can be created with approval of your instructor and needs to be large in scope. A team of 5 students or more is not allowed. Record your team [here](https://docs.google.com/spreadsheets/d/1BK1E7BxYBo5eVU2Vq7N6vOaKiWkZ8tRKdSukUWAp4KM/edit?usp=sharing).
- Create a new GitHub repository for your team in the UC-Berkeley-I-School organization. Name this folder as Project2 plus each last name of the students in the group like: **Project2_Foster_Kleemann_Llop**; please make this repo PRIVATE and invite the Instructor team / the rest of your team members.
- You can choose your team members from among students in your section, or in exceptional cases from among students in other sections. (Please email **both** section instructors to get an OK)

#### Data Analysis
- This project is relatively unguided. You will come up with your own interesting questions that you can answer using the variables in your dataset, then perform an analysis based on those questions.
- You can analyze either an *instructor-approved dataset of your finding* or one that we have pre-approved. You may join several datasets together. For example, you might combine two datasets to answer questions like, "Is felony crime higher in NYC after 2 days of rain?"
- This project emphasizes the exploratory and descriptive techniques covered in class. Although some of you have a background in statistics, we ask that you avoid any statistical inference or other advanced techniques. In particular, this means that you should confine your analysis to the sample of data you have, and avoid making statements about the population that the sample comes from.

#### Proposal (10%)
With your team members, prepare a 1 to 2 page proposal about the questions that you intend to ask of the data. 

The proposal should describe:

- Names of team members,
- Name of your team's GitHub repository,
- A primary dataset you intend to analyze,
- Initial plots, figures, or tables,
- Some of the variables (column names) you intend to explore and what kind of insights you expect to glean,
- Supplemental datasets, if any, to complement your primary dataset - this means links, columns that you'll join on, etc.,
- What you plan to cover in the final report and how you plan to organize it.

#### In-Class Presentation (20%)
The final class will include a 10 minute presentation per group with a 5 minute question/answer period. The presentation should include:
- Your overall question
- The steps your group took to analyze the question
- Any assumptions you made in the analysis
- The key is to aim for clarity and telling a story with the data
- Organize your argument clearly
- Guide the listeners through the evidence in the data
- Include any key figures/plots/charts or graphs
- You do not need to show any code but it might be handy to have the code ready in case there are some questions on it

#### Report (70%)

Grading Breakdown:
- 10% Questions
- 20% Data Cleaning / Sanity Checks
- 20% Compelling Text and Data Stories
- 20% Compelling Figures

Your report should be 8-10 pages (including appropriately sized figures) and describe what you found out from the data. This should focus on telling stories and explaining the narrative of the exploration and challenges associated with that. The report should not include any code - rather, all code should be included in a sub-folder in either plain python files or in jupyter notebooks. If your report contents are over 8-10 pages, please edit to include the most important material in the first 8-10 pages and any extra material in the Appendix. 

For the report, any figure/plot/chart/graph should be annotated with descriptions about why they are included.

Note: Using GitHub to share jupyter notebooks has proven problematic in the past. Be sure to create copies of notebooks when you make an edit.  As your code becomes increasingly stable, you may find it easier to just put it into a python file and import it into a jupyter notebook as needed.

Points for the report:
- Your analysis is a written argument.
- The key is to aim for clarity and exposition.
- Organize your argument clearly
- Guide the reader through the evidence in the data.
- Proofread!
- Every figure/plot/chart/graph in the report should be mentioned in your writing, explain what it means
- If you don’t have something to say about your figure/plot/chart/graph, don’t display it at all.
- No output dumps
- Document decisions
  - If you decide that observations should be removed, state which ones.
  - If values are suspicious, but you leave them in, state that too.
  - If you transform a variable, for example, by taking the logarithm, state that.
  - Your justification can often be very brief (just a sentence), but make sure the reader can follow your logic.
- Characterize relationships between variables
  - Keep in mind the purpose of the analysis.  
  - For example, if you’re interested in explaining the price of a house, look to see what kind of relationship that variable has with the other variables.
- Use only descriptive statistics
  - Descriptive statistics summarize a particular sample of data.
  - In the field of inferential statistics (which you’ll learn in w203) you’ll see how to create a model that represents the population (or process) from which the sample came from, and to make assertions about that population.
  - Since we haven’t taught you any inference, please don’t use it.
  - Beware of the word ‘significant’
    - This has a technical meaning, implying that you’ve performed a statistical test


## Instructor Pre-Approved Datasets
- [Political Ad Archive](http://politicaladarchive.org/data/)
- [Global warming data (Berkeley Earth) - use the *time series section* ](http://berkeleyearth.org/data/)
- [US Gov't Web Logs](https://analytics.usa.gov/)
- [Parks graffitti report (St. Paul)](https://information.stpaul.gov/City-Infrastructure/Parks-Graffiti-Report-Dataset/gcu2-spkd) 
- [The National UFO Reporting Center Online Database](http://www.nuforc.org) will be challenging but fun since the reports are not uniform and are split across multiple tables that you may have to scrape.

## Other Datasets
**REMEMBER NONE OF THESE HAVE BEEN APPROVED, YOU HAVE TO TALK TO YOUR INSTRUCTOR TO GET THEM APPROVED.**

- [Historical Weather Data](https://www.ncdc.noaa.gov/data-access/land-based-station-data/land-based-datasets/global-historical-climatology-network-ghcn)
  - This can be a bit difficult to figure out what to download. [In this discussion](https://news.ycombinator.com/item?id=10465342) there are some pointers on how to get at it. This dataset is pre-approved as a **supplemental** dataset, but see your instructor if you would like this to be the primary dataset.
- [Data is Plural](http://tinyletter.com/data-is-plural/archive)
  - The pre-approved datasets come primarily from here. Pretty extensive list.
- [Awesome Public Datasets](https://github.com/caesar0301/awesome-public-datasets)
  - Awesome list that's worth saving for future reference. Be sure to actually download and explore the data before proposing one to your instructor. There are some awesome datasets here like the NYC taxi dataset.
- [Data.gov](http://data.gov/)
  - All government data, which is good!
- [Reddit/r/Datasets](https://www.reddit.com/r/datasets)
  - Community-generated and definitely some potential for good datasets.
  
#### To get a dataset approved ...
1. Send your instructor a description of the data, including a link to the exact dataset or a place from where it can be downloaded with one click without registering (or anything like that). 
    - The data needs to be in a raw text file format like json or csv (or at least very easy to convert to that format).
    - Report the size of the dataset or the subset you plan on looking at. This is **not** a big data project.
2. Show that you've done some preliminary research and that there will be enough interesting questions to ask of the data. This should include column names and information about any missing data.

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
#clean 2016Q4 data
house2016Q4_detail = pd.read_csv("2016Q4-house-disburse-detail.csv")
personnelcompensation16Q4 = house2016Q4_detail.loc[house2016Q4_detail['CATEGORY'] == 'PERSONNEL COMPENSATION']
personnelcompensationb16Q4 = personnelcompensation16Q4.loc[personnelcompensation16Q4['AMOUNT'] > 0]
payee2016Q4 = personnelcompensationb16Q4.loc[:, ['OFFICE','PAYEE']].drop_duplicates(subset=['PAYEE'])
payee2016Q4['Period'] = '2016 Q4'
staffcount16Q4 = personnelcompensationb16Q4['PURPOSE'].value_counts().rename_axis('Position').reset_index(name='count')
staffcomp16Q4 = personnelcompensationb16Q4.groupby(['PURPOSE'])['AMOUNT'].agg('sum').rename_axis('Position').reset_index(name='total compensation')
staffsalary2016Q4 = pd.merge(left=staffcount16Q4, right=staffcomp16Q4, on='Position', how='inner')
staffsalary2016Q4['avg salary'] = staffsalary2016Q4['total compensation'] / staffsalary2016Q4['count']
staffsalary2016Q4['Period'] = '2016 Q4' 
staffsalary2016Q4.sort_values(['avg salary'], ascending=False).head(10)
staffsalary2016Q4 = staffsalary2016Q4[~staffsalary2016Q4['Position'].str.contains('(OVERTIME)')]
staffsalary2016Q4 = staffsalary2016Q4[~staffsalary2016Q4['Position'].str.contains('(OTHER COMPENSATION)')]
staffsalary2016Q4 = staffsalary2016Q4[~staffsalary2016Q4['Position'].str.contains('(ASST)')]
staffsalary2016Q4.sort_values(['avg salary'], ascending=True).head(15)
#personnelcompensation16Q4.loc[personnelcompensation16Q4['AMOUNT'] < 0]

/var/folders/jr/dnsfm9kj2575clb1_33r_09w0000gn/T/ipykernel_42049/1463901125.py:12: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  staffsalary2016Q4 = staffsalary2016Q4[~staffsalary2016Q4['Position'].str.contains('(OVERTIME)')]
/var/folders/jr/dnsfm9kj2575clb1_33r_09w0000gn/T/ipykernel_42049/1463901125.py:13: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  staffsalary2016Q4 = staffsalary2016Q4[~staffsalary2016Q4['Position'].str.contains('(OTHER COMPENSATION)')]
/var/folders/jr/dnsfm9kj2575clb1_33r_09w0000gn/T/ipykernel_42049/1463901125.py:14: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  staffsalary2016Q4 = staffsalary2016Q4[~staffsalary2016Q4['Position'].str.contains('(ASST)')]

,Position,count,total compensation,avg salary,Period
846,DIRECTOR OF CONSTITUENT RELATI,1,125.00,125.00,2016 Q4
2132,NDC PRESS SECRETARY/COMMS AIDE,1,300.00,300.00,2016 Q4
1184,COMMITTEE LIAISON,1,300.00,300.00,2016 Q4
1889,DIRECTOR MEMBERS' SERVICES,1,413.33,413.33,2016 Q4
2272,IT SUPPORT,1,450.00,450.00,2016 Q4
877,STRATEGIC DIRECTOR,1,666.67,666.67,2016 Q4
2118,HOMELAND SECURITY ADVISOR,1,680.17,680.17,2016 Q4
1708,ADV FOR MEMBER SERVICES,1,995.00,995.00,2016 Q4
879,LEGISLATIVE DIRECTOR NEMW,1,1000.00,1000.00,2016 Q4
786,EXECUTIVE DIRECTOR-CHC,1,1100.01,1100.01,2016 Q4
2050,DISTRICT OFFICE SCHEDULER,1,1205.56,1205.56,2016 Q4
1075,SELECT PANEL COUNSEL,1,1250.01,1250.01,2016 Q4
1055,STAFF DIRECTOR/GENERAL COUNSEL,1,1250.01,1250.01,2016 Q4
808,SCHEDULER/NEW MEDIA COORD,1,1265.31,1265.31,2016 Q4
915,DIGITAL INTERN,1,1333.33,1333.33,2016 Q4

In [ ]:
#clean 2016Q1 data
house2016Q1_detail = pd.read_csv("2016Q1-house-disburse-detail.csv")
house2016Q1_detail['AMOUNT'] = house2016Q1_detail['AMOUNT'].astype(str).str.replace(',','').astype(float)
personnelcompensation16Q1 = house2016Q1_detail.loc[house2016Q1_detail['CATEGORY'] == 'PERSONNEL COMPENSATION']
personnelcompensationb16Q1 = personnelcompensation16Q1.loc[personnelcompensation16Q1['AMOUNT'] > 0]
payee2016Q1 = personnelcompensationb16Q1.loc[:, ['OFFICE','PAYEE']].drop_duplicates(subset=['PAYEE'])
payee2016Q1['Period'] = '2016 Q1'
staffcount16Q1 = personnelcompensationb16Q1['PURPOSE'].value_counts().rename_axis('Position').reset_index(name='count')
staffcomp16Q1 = personnelcompensationb16Q1.groupby(['PURPOSE'])['AMOUNT'].agg('sum').rename_axis('Position').reset_index(name='total compensation')
staffsalary2016Q1 = pd.merge(left=staffcount16Q1, right=staffcomp16Q1, on='Position', how='inner')
staffsalary2016Q1['avg salary'] = staffsalary2016Q1['total compensation'] / staffsalary2016Q1['count']
staffsalary2016Q1['Period'] = '2016 Q1' 
staffsalary2016Q1 = staffsalary2016Q1[~staffsalary2016Q1['Position'].str.contains('(OVERTIME)')]
staffsalary2016Q1 = staffsalary2016Q1[~staffsalary2016Q1['Position'].str.contains('(OTHER COMPENSATION)')]
staffsalary2016Q1 = staffsalary2016Q1[~staffsalary2016Q1['Position'].str.contains('(ASST)')]
staffsalary2016Q1.sort_values(['avg salary'], ascending=True).head(15)

/var/folders/jr/dnsfm9kj2575clb1_33r_09w0000gn/T/ipykernel_42049/3002962163.py:12: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  staffsalary2016Q1 = staffsalary2016Q1[~staffsalary2016Q1['Position'].str.contains('(OVERTIME)')]
/var/folders/jr/dnsfm9kj2575clb1_33r_09w0000gn/T/ipykernel_42049/3002962163.py:13: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  staffsalary2016Q1 = staffsalary2016Q1[~staffsalary2016Q1['Position'].str.contains('(OTHER COMPENSATION)')]
/var/folders/jr/dnsfm9kj2575clb1_33r_09w0000gn/T/ipykernel_42049/3002962163.py:14: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  staffsalary2016Q1 = staffsalary2016Q1[~staffsalary2016Q1['Position'].str.contains('(ASST)')]

,Position,count,total compensation,avg salary,Period
1167,COMMITTEE LIAISON,2,283.33,141.665,2016 Q1
608,DEPUTY COS/FLOOR DIRECTOR,2,300.00,150.000,2016 Q1
1557,DEMO DTY STAFF DIR CHIEF COUN,2,300.00,150.000,2016 Q1
780,SR ADVISOR/COMMUNICA DIR,2,303.82,151.910,2016 Q1
2003,PART TIME STAFF,1,165.12,165.120,2016 Q1
2176,SR. CONSTITUENT ADVOC./F. REP,1,194.44,194.440,2016 Q1
1528,BONUS,2,427.60,213.800,2016 Q1
633,IT SUPPORT,2,450.00,225.000,2016 Q1
1500,COALITIONS AND OUTREACH COORD,2,541.67,270.835,2016 Q1
2054,DISTRICT STAFF ASSIST,1,291.67,291.670,2016 Q1
713,DEPUTY OVERSIGHT COUNSEL-LA,2,666.67,333.335,2016 Q1
958,COMMUNICATIONS DIRECTOR-CHC,2,699.99,349.995,2016 Q1
2051,PART TIME LEGISLATIVE CORR,1,364.58,364.580,2016 Q1
579,OCEAN POLICY ADVISOR,2,1000.00,500.000,2016 Q1
934,CASE MANAGER,2,1069.44,534.720,2016 Q1

In [ ]:
#clean 2016Q1 data
house2016Q2_detail = pd.read_csv("2016Q2-house-disburse-detail.csv")
house2016Q2_detail['AMOUNT'] = house2016Q2_detail['AMOUNT'].astype(str).str.replace(',','').astype(float)
personnelcompensation16Q2 = house2016Q2_detail.loc[house2016Q2_detail['CATEGORY'] == 'PERSONNEL COMPENSATION']
personnelcompensationb16Q2 = personnelcompensation16Q2.loc[personnelcompensation16Q2['AMOUNT'] > 0]
payee2016Q2 = personnelcompensationb16Q2.loc[:, ['OFFICE','PAYEE']].drop_duplicates(subset=['PAYEE'])
payee2016Q2['Period'] = '2016 Q2'
staffcount16Q2 = personnelcompensationb16Q2['PURPOSE'].value_counts().rename_axis('Position').reset_index(name='count')
staffcomp16Q2 = personnelcompensationb16Q2.groupby(['PURPOSE'])['AMOUNT'].agg('sum').rename_axis('Position').reset_index(name='total compensation')
staffsalary2016Q2 = pd.merge(left=staffcount16Q2, right=staffcomp16Q2, on='Position', how='inner')
staffsalary2016Q2['avg salary'] = staffsalary2016Q2['total compensation'] / staffsalary2016Q2['count']
staffsalary2016Q2['Period'] = '2016 Q2' 
staffsalary2016Q2.sort_values(['avg salary'], ascending=False).head(10)
staffsalary2016Q2 = staffsalary2016Q2[~staffsalary2016Q2['Position'].str.contains('(OVERTIME)')]
staffsalary2016Q2 = staffsalary2016Q2[~staffsalary2016Q2['Position'].str.contains('(OTHER COMPENSATION)')]
staffsalary2016Q2 = staffsalary2016Q2[~staffsalary2016Q2['Position'].str.contains('(ASST)')]
staffsalary2016Q2.sort_values(['avg salary'], ascending=True).head(15)
payee2016Q2

/var/folders/jr/dnsfm9kj2575clb1_33r_09w0000gn/T/ipykernel_42049/3546079287.py:13: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  staffsalary2016Q2 = staffsalary2016Q2[~staffsalary2016Q2['Position'].str.contains('(OVERTIME)')]
/var/folders/jr/dnsfm9kj2575clb1_33r_09w0000gn/T/ipykernel_42049/3546079287.py:14: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  staffsalary2016Q2 = staffsalary2016Q2[~staffsalary2016Q2['Position'].str.contains('(OTHER COMPENSATION)')]
/var/folders/jr/dnsfm9kj2575clb1_33r_09w0000gn/T/ipykernel_42049/3546079287.py:15: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  staffsalary2016Q2 = staffsalary2016Q2[~staffsalary2016Q2['Position'].str.contains('(ASST)')]

                               OFFICE                PAYEE   Period
0               OFFICE OF THE SPEAKER    ALTHOUSE,JOSHUA S  2016 Q2
1               OFFICE OF THE SPEAKER     ANDRES,DOUGLAS R  2016 Q2
2               OFFICE OF THE SPEAKER     ANDREWS,THOMAS S  2016 Q2
3               OFFICE OF THE SPEAKER      ANTELL,GEOFFREY  2016 Q2
4               OFFICE OF THE SPEAKER  BENJAMIN, WILLIAM C  2016 Q2
...                               ...                  ...      ...
98859  OFFICE OF CONGRESSIONAL ETHICS          CHO,HEEJUNG  2016 Q2
98860  OFFICE OF CONGRESSIONAL ETHICS       EISNER,HELEN P  2016 Q2
98861  OFFICE OF CONGRESSIONAL ETHICS     FLANAGAN, MARY K  2016 Q2
98862  OFFICE OF CONGRESSIONAL ETHICS           GAST,SCOTT  2016 Q2
98863  OFFICE OF CONGRESSIONAL ETHICS         SOLIS,PAUL J  2016 Q2

[10067 rows x 3 columns]

In [ ]:
#clean 2016Q3 data
house2016Q3_detail = pd.read_csv("2016Q3-house-disburse-detail.csv")
house2016Q3_detail['AMOUNT'] = house2016Q3_detail['AMOUNT'].astype(str).str.replace(',','').astype(float)
personnelcompensation16Q3 = house2016Q3_detail.loc[house2016Q3_detail['CATEGORY'] == 'PERSONNEL COMPENSATION']
personnelcompensationb16Q3 = personnelcompensation16Q3.loc[personnelcompensation16Q3['AMOUNT'] > 0]
payee2016Q3 = personnelcompensationb16Q3.loc[:, ['OFFICE','PAYEE']].drop_duplicates(subset=['PAYEE'])
payee2016Q3['Period'] = '2016 Q3'
staffcount16Q3 = personnelcompensationb16Q3['PURPOSE'].value_counts().rename_axis('Position').reset_index(name='count')
staffcomp16Q3 = personnelcompensationb16Q3.groupby(['PURPOSE'])['AMOUNT'].agg('sum').rename_axis('Position').reset_index(name='total compensation')
staffsalary2016Q3 = pd.merge(left=staffcount16Q3, right=staffcomp16Q3, on='Position', how='inner')
staffsalary2016Q3['avg salary'] = staffsalary2016Q3['total compensation'] / staffsalary2016Q3['count']
staffsalary2016Q3['Period'] = '2016 Q3' 
staffsalary2016Q3.sort_values(['avg salary'], ascending=False).head(10)
staffsalary2016Q3 = staffsalary2016Q3[~staffsalary2016Q3['Position'].str.contains('(OVERTIME)')]
staffsalary2016Q3 = staffsalary2016Q3[~staffsalary2016Q3['Position'].str.contains('(OTHER COMPENSATION)')]
staffsalary2016Q3 = staffsalary2016Q3[~staffsalary2016Q3['Position'].str.contains('(ASST)')]
staffsalary2016Q3.sort_values(['avg salary'], ascending=True).head(15)
payee2016Q3

/var/folders/jr/dnsfm9kj2575clb1_33r_09w0000gn/T/ipykernel_42049/958524741.py:13: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  staffsalary2016Q3 = staffsalary2016Q3[~staffsalary2016Q3['Position'].str.contains('(OVERTIME)')]
/var/folders/jr/dnsfm9kj2575clb1_33r_09w0000gn/T/ipykernel_42049/958524741.py:14: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  staffsalary2016Q3 = staffsalary2016Q3[~staffsalary2016Q3['Position'].str.contains('(OTHER COMPENSATION)')]
/var/folders/jr/dnsfm9kj2575clb1_33r_09w0000gn/T/ipykernel_42049/958524741.py:15: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  staffsalary2016Q3 = staffsalary2016Q3[~staffsalary2016Q3['Position'].str.contains('(ASST)')]

                               OFFICE                PAYEE   Period
1               OFFICE OF THE SPEAKER    ALTHOUSE,JOSHUA S  2016 Q3
2               OFFICE OF THE SPEAKER     ANDRES,DOUGLAS R  2016 Q3
3               OFFICE OF THE SPEAKER     ANDREWS,THOMAS S  2016 Q3
4               OFFICE OF THE SPEAKER      ANTELL,GEOFFREY  2016 Q3
5               OFFICE OF THE SPEAKER  BENJAMIN, WILLIAM C  2016 Q3
...                               ...                  ...      ...
92169  OFFICE OF CONGRESSIONAL ETHICS          CHO,HEEJUNG  2016 Q3
92170  OFFICE OF CONGRESSIONAL ETHICS       EISNER,HELEN P  2016 Q3
92171  OFFICE OF CONGRESSIONAL ETHICS     FLANAGAN, MARY K  2016 Q3
92172  OFFICE OF CONGRESSIONAL ETHICS           GAST,SCOTT  2016 Q3
92173  OFFICE OF CONGRESSIONAL ETHICS         SOLIS,PAUL J  2016 Q3

[10058 rows x 3 columns]

In [ ]:
#clean 2017Q1 data
house2017Q1_detail = pd.read_csv("2017Q1-house-disburse-detail.csv")
personnelcompensation17Q1 = house2017Q1_detail.loc[house2017Q1_detail['CATEGORY'] == 'PERSONNEL COMPENSATION']
personnelcompensationb17Q1 = personnelcompensation17Q1.loc[personnelcompensation17Q1['AMOUNT'] >0]
payee2017Q1 = personnelcompensationb17Q1.loc[:, ['OFFICE','PAYEE']].drop_duplicates(subset=['PAYEE'])
payee2017Q1['Period'] = '2017 Q1'
staffcount17Q1 = personnelcompensationb17Q1['PURPOSE'].value_counts().rename_axis('Position').reset_index(name='count')
staffcomp17Q1 = personnelcompensationb17Q1.groupby(['PURPOSE'])['AMOUNT'].agg('sum').rename_axis('Position').reset_index(name='total compensation')
staffsalary2017Q1 = pd.merge(left=staffcount17Q1, right=staffcomp17Q1, on='Position', how='inner')
staffsalary2017Q1['avg salary'] = staffsalary2017Q1['total compensation'] / staffsalary2017Q1['count']
staffsalary2017Q1['Period'] = '2017 Q1' 
staffsalary2017Q1.sort_values(['avg salary'], ascending=False).head(10)
staffsalary2016Q1 = staffsalary2016Q1[~staffsalary2016Q1['Position'].str.contains('(OVERTIME)')]
staffsalary2016Q1 = staffsalary2016Q1[~staffsalary2016Q1['Position'].str.contains('(OTHER COMPENSATION)')]
staffsalary2016Q1 = staffsalary2016Q1[~staffsalary2016Q1['Position'].str.contains('(ASST)')]
staffsalary2016Q1.sort_values(['avg salary'], ascending=True).head(15)
payee2017Q1

/var/folders/jr/dnsfm9kj2575clb1_33r_09w0000gn/T/ipykernel_42049/2983500141.py:12: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  staffsalary2016Q1 = staffsalary2016Q1[~staffsalary2016Q1['Position'].str.contains('(OVERTIME)')]
/var/folders/jr/dnsfm9kj2575clb1_33r_09w0000gn/T/ipykernel_42049/2983500141.py:13: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  staffsalary2016Q1 = staffsalary2016Q1[~staffsalary2016Q1['Position'].str.contains('(OTHER COMPENSATION)')]
/var/folders/jr/dnsfm9kj2575clb1_33r_09w0000gn/T/ipykernel_42049/2983500141.py:14: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  staffsalary2016Q1 = staffsalary2016Q1[~staffsalary2016Q1['Position'].str.contains('(ASST)')]

                                OFFICE                PAYEE   Period
0                OFFICE OF THE SPEAKER    ALTHOUSE JOSHUA S  2017 Q1
1                OFFICE OF THE SPEAKER     ANDRES DOUGLAS R  2017 Q1
2                OFFICE OF THE SPEAKER     ANDREWS THOMAS S  2017 Q1
3                OFFICE OF THE SPEAKER      ANTELL GEOFFREY  2017 Q1
4                OFFICE OF THE SPEAKER  BENJAMIN WILLIAM C.  2017 Q1
...                                ...                  ...      ...
102722  OFFICE OF CONGRESSIONAL ETHICS          CHO HEEJUNG  2017 Q1
102723  OFFICE OF CONGRESSIONAL ETHICS       EISNER HELEN P  2017 Q1
102724  OFFICE OF CONGRESSIONAL ETHICS           GAST SCOTT  2017 Q1
102725  OFFICE OF CONGRESSIONAL ETHICS         SOLIS PAUL J  2017 Q1
102730  OFFICE OF CONGRESSIONAL ETHICS       PAYNE KEDRIC L  2017 Q1

[10310 rows x 3 columns]

In [ ]:
#clean 2017Q3 data
house2017Q3_detail = pd.read_csv("2017Q3-house-disburse-detail.csv")
personnelcompensationQ317 = house2017Q3_detail.loc[house2017Q3_detail['CATEGORY'] == 'PERSONNEL COMPENSATION']
personnelcompensationbQ317 = personnelcompensationQ317.loc[personnelcompensationQ317['AMOUNT'] >0]
payee2017Q3 = personnelcompensationbQ317.loc[:, ['OFFICE','PAYEE']].drop_duplicates(subset=['PAYEE'])
payee2017Q3['Period'] = '2017 Q3'
staffcountQ317 = personnelcompensationbQ317['PURPOSE'].value_counts().rename_axis('Position').reset_index(name='count')
staffcompQ317 = personnelcompensationbQ317.groupby(['PURPOSE'])['AMOUNT'].agg('sum').rename_axis('Position').reset_index(name='total compensation')
staffsalary2017Q3 = pd.merge(left=staffcountQ317, right=staffcompQ317, on='Position', how='inner')
staffsalary2017Q3['avg salary'] = staffsalary2017Q3['total compensation'] / staffsalary2017Q3['count']
staffsalary2017Q3['Period'] = '2017 Q3'
#staffsalary2017Q3['Position'] = staffsalary2017Q3['Position'].astype(str)
staffsalary2017Q3 = staffsalary2017Q3[~staffsalary2017Q3["Position"].str.contains('TOTALS:')]
staffsalary2017Q3.sort_values(['avg salary'], ascending=False).head(10)
staffsalary2017Q3 = staffsalary2017Q3[~staffsalary2017Q3['Position'].str.contains('(OVERTIME)')]
staffsalary2017Q3 = staffsalary2017Q3[~staffsalary2017Q3['Position'].str.contains('(OTHER COMPENSATION)')]
staffsalary2017Q3 = staffsalary2017Q3[~staffsalary2017Q3['Position'].str.contains('(ASST)')]
staffsalary2017Q3.sort_values(['avg salary'], ascending=True).head(15)
personnelcompensationbQ317.loc[personnelcompensationbQ317['OFFICE'] == '2017 HON. DIANE BLACK']

/var/folders/jr/dnsfm9kj2575clb1_33r_09w0000gn/T/ipykernel_42049/1798297979.py:14: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  staffsalary2017Q3 = staffsalary2017Q3[~staffsalary2017Q3['Position'].str.contains('(OVERTIME)')]
/var/folders/jr/dnsfm9kj2575clb1_33r_09w0000gn/T/ipykernel_42049/1798297979.py:15: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  staffsalary2017Q3 = staffsalary2017Q3[~staffsalary2017Q3['Position'].str.contains('(OTHER COMPENSATION)')]
/var/folders/jr/dnsfm9kj2575clb1_33r_09w0000gn/T/ipykernel_42049/1798297979.py:16: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  staffsalary2017Q3 = staffsalary2017Q3[~staffsalary2017Q3['Position'].str.contains('(ASST)')]

,BIOGUIDE_ID,OFFICE,QUARTER,PROGRAM,CATEGORY,SORT SEQUENCE,DATE,TRANSCODE,RECORDID,PAYEE,START DATE,END DATE,PURPOSE,AMOUNT,YEAR
10832,B001273,2017 HON. DIANE BLACK,Q3,OFFICIAL EXPENSES OF MEMBERS,PERSONNEL COMPENSATION,DETAIL,,,,AYERS NICHOLAS A,8/30/2017,9/30/2017,STAFF ASSISTANT,2841.67,2017
10833,B001273,2017 HON. DIANE BLACK,Q3,OFFICIAL EXPENSES OF MEMBERS,PERSONNEL COMPENSATION,DETAIL,,,,BALCH KENNA C,7/1/2017,9/30/2017,CASEWORKER,9099.99,2017
10834,B001273,2017 HON. DIANE BLACK,Q3,OFFICIAL EXPENSES OF MEMBERS,PERSONNEL COMPENSATION,DETAIL,,,,BUCK EMILY A,7/1/2017,9/30/2017,FIELD REPRESENTATIVE,9785.01,2017
10835,B001273,2017 HON. DIANE BLACK,Q3,OFFICIAL EXPENSES OF MEMBERS,PERSONNEL COMPENSATION,DETAIL,,,,BURCH LEIGH A,7/1/2017,9/30/2017,LEGISLATIVE ASSISTANT,10125.00,2017
10836,B001273,2017 HON. DIANE BLACK,Q3,OFFICIAL EXPENSES OF MEMBERS,PERSONNEL COMPENSATION,DETAIL,,,,DETWILER MICHAEL,7/1/2017,9/30/2017,FIELD REPRESENTATIVE,14475.00,2017
10837,B001273,2017 HON. DIANE BLACK,Q3,OFFICIAL EXPENSES OF MEMBERS,PERSONNEL COMPENSATION,DETAIL,,,,DONCHES MICHELLE M.,7/1/2017,9/30/2017,SHARED EMPLOYEE,3750.00,2017
10838,B001273,2017 HON. DIANE BLACK,Q3,OFFICIAL EXPENSES OF MEMBERS,PERSONNEL COMPENSATION,DETAIL,,,,DOUGLASS HEATHER M,7/1/2017,9/30/2017,PRESS SECRETARY,13500.00,2017
10839,B001273,2017 HON. DIANE BLACK,Q3,OFFICIAL EXPENSES OF MEMBERS,PERSONNEL COMPENSATION,DETAIL,,,,DOWELL STANLEY G,7/1/2017,9/30/2017,SCHEDULER,12225.00,2017
10840,B001273,2017 HON. DIANE BLACK,Q3,OFFICIAL EXPENSES OF MEMBERS,PERSONNEL COMPENSATION,DETAIL,,,,HELTON JOSHUA M,7/1/2017,9/30/2017,SENIOR ADVISOR,24999.99,2017
10841,B001273,2017 HON. DIANE BLACK,Q3,OFFICIAL EXPENSES OF MEMBERS,PERSONNEL COMPENSATION,DETAIL,,,,JONES RACHEL A,7/1/2017,8/31/2017,STAFF ASSISTANT,5000.00,2017
10842,B001273,2017 HON. DIANE BLACK,Q3,OFFICIAL EXPENSES OF MEMBERS,PERSONNEL COMPENSATION,DETAIL,,,,KOEBERLEIN TERESA R,7/1/2017,9/30/2017,CHIEF OF STAFF,39999.99,2017
10843,B001273,2017 HON. DIANE BLACK,Q3,OFFICIAL EXPENSES OF MEMBERS,PERSONNEL COMPENSATION,DETAIL,,,,LASSITER HILLARY W,7/1/2017,9/30/2017,LEGISLATIVE ASST/PRESS ASST,10500.00,2017
10844,B001273,2017 HON. DIANE BLACK,Q3,OFFICIAL EXPENSES OF MEMBERS,PERSONNEL COMPENSATION,DETAIL,,,,MITCHELL KATIE B,7/1/2017,8/2/2017,POLICY ADVISOR,4160.00,2017
10845,B001273,2017 HON. DIANE BLACK,Q3,OFFICIAL EXPENSES OF MEMBERS,PERSONNEL COMPENSATION,DETAIL,,,,ROYSTER ZACHARY H,7/1/2017,8/31/2017,STAFF ASSISTANT,5666.66,2017
10846,B001273,2017 HON. DIANE BLACK,Q3,OFFICIAL EXPENSES OF MEMBERS,PERSONNEL COMPENSATION,DETAIL,,,,ROYSTER ZACHARY H,8/1/2017,9/30/2017,LEGISLATIVE CORRESPONDENT,3055.56,2017
10847,B001273,2017 HON. DIANE BLACK,Q3,OFFICIAL EXPENSES OF MEMBERS,PERSONNEL COMPENSATION,DETAIL,,,,THOMPSON DEAN J,7/1/2017,9/30/2017,DEPUTY CHIEF OF STAFF,22777.78,2017
10848,B001273,2017 HON. DIANE BLACK,Q3,OFFICIAL EXPENSES OF MEMBERS,PERSONNEL COMPENSATION,DETAIL,,,,TOOMEY JONATHAN M,7/1/2017,9/4/2017,LEGISLATIVE COUNSEL,8711.10,2017
10849,B001273,2017 HON. DIANE BLACK,Q3,OFFICIAL EXPENSES OF MEMBERS,PERSONNEL COMPENSATION,DETAIL,,,,WARREN BONNY,7/1/2017,9/30/2017,CASEWORKER,10749.99,2017
10850,B001273,2017 HON. DIANE BLACK,Q3,OFFICIAL EXPENSES OF MEMBERS,PERSONNEL COMPENSATION,SUBTOTAL,,,,,,,PERSONNEL COMPENSATION TOTALS:,211422.74,#VALUE!

In [ ]:
#clean 2017Q4 data
house2017Q4_detail = pd.read_csv("2017Q4-house-disburse-detail.csv")
personnelcompensationQ417 = house2017Q4_detail.loc[house2017Q4_detail['CATEGORY'] == 'PERSONNEL COMPENSATION']
personnelcompensationbQ417 = personnelcompensationQ417.loc[personnelcompensationQ417['AMOUNT'] >0]
payee2017Q4 = personnelcompensationbQ417.loc[:, ['OFFICE','PAYEE']].drop_duplicates(subset=['PAYEE'])
payee2017Q4['Period'] = '2017 Q4'
staffcountQ417 = personnelcompensationbQ417['PURPOSE'].value_counts().rename_axis('Position').reset_index(name='count')
staffcompQ417 = personnelcompensationbQ417.groupby(['PURPOSE'])['AMOUNT'].agg('sum').rename_axis('Position').reset_index(name='total compensation')
staffsalary2017Q4 = pd.merge(left=staffcountQ417, right=staffcompQ417, on='Position', how='inner')
staffsalary2017Q4['avg salary'] = staffsalary2017Q4['total compensation'] / staffsalary2017Q4['count']
staffsalary2017Q4['Period'] = '2017 Q4'
#staffsalary2017Q3['Position'] = staffsalary2017Q3['Position'].astype(str)
staffsalary2017Q4 = staffsalary2017Q4[~staffsalary2017Q4["Position"].str.contains('TOTALS:')]
staffsalary2017Q4.sort_values(['avg salary'], ascending=False).head(10)
staffsalary2017Q4 = staffsalary2017Q4[~staffsalary2017Q4['Position'].str.contains('(OVERTIME)')]
staffsalary2017Q4 = staffsalary2017Q4[~staffsalary2017Q4['Position'].str.contains('(OTHER COMPENSATION)')]
staffsalary2017Q4 = staffsalary2017Q4[~staffsalary2017Q4['Position'].str.contains('(ASST)')]
staffsalary2017Q4.sort_values(['avg salary'], ascending=True).head(15)
payee2017Q4

/var/folders/jr/dnsfm9kj2575clb1_33r_09w0000gn/T/ipykernel_42049/1614660162.py:14: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  staffsalary2017Q4 = staffsalary2017Q4[~staffsalary2017Q4['Position'].str.contains('(OVERTIME)')]
/var/folders/jr/dnsfm9kj2575clb1_33r_09w0000gn/T/ipykernel_42049/1614660162.py:15: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  staffsalary2017Q4 = staffsalary2017Q4[~staffsalary2017Q4['Position'].str.contains('(OTHER COMPENSATION)')]
/var/folders/jr/dnsfm9kj2575clb1_33r_09w0000gn/T/ipykernel_42049/1614660162.py:16: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  staffsalary2017Q4 = staffsalary2017Q4[~staffsalary2017Q4['Position'].str.contains('(ASST)')]

,OFFICE,PAYEE,Period
0,2017 OFFICE OF THE SPEAKER,ALTHOUSE JOSHUA S,2017 Q4
1,2017 OFFICE OF THE SPEAKER,ANDRES DOUGLAS R,2017 Q4
2,2017 OFFICE OF THE SPEAKER,ANDREWS THOMAS S,2017 Q4
3,2017 OFFICE OF THE SPEAKER,ANTELL GEOFFREY,2017 Q4
4,2017 OFFICE OF THE SPEAKER,BENJAMIN WILLIAM C.,2017 Q4
...,...,...,...
99673,FISCAL YEAR 2018 OFFICE OF CONGRESSIONAL ETHICS,BREWINGTON KELLY D,2017 Q4
99674,FISCAL YEAR 2018 OFFICE OF CONGRESSIONAL ETHICS,BROWN JEFFREY L,2017 Q4
99675,FISCAL YEAR 2018 OFFICE OF CONGRESSIONAL ETHICS,CHO HEEJUNG,2017 Q4
99676,FISCAL YEAR 2018 OFFICE OF CONGRESSIONAL ETHICS,EISNER HELEN P,2017 Q4
99677,FISCAL YEAR 2018 OFFICE OF CONGRESSIONAL ETHICS,SOLIS PAUL J,2017 Q4

In [ ]:
#clean 2017Q2 data
house2017Q2_detail = pd.read_csv("2017Q2-house-disburse-detail.csv",encoding= 'unicode_escape')
house2017Q2_detail = house2017Q2_detail.rename(columns={"RECORDID": "PAYEE", "PAYEE": "START DATE", "START DATE": "END DATE", "END DATE": "PURPOSE", "PURPOSE": "AMOUNT", "AMOUNT": "YEAR1"})
house2017Q2_detail = house2017Q2_detail.drop('YEAR', 1)
house2017Q2_detail = house2017Q2_detail.rename(columns={"YEAR1": "YEAR"})
personnelcompensationQ217 = house2017Q2_detail.loc[house2017Q2_detail['CATEGORY'] == 'PERSONNEL COMPENSATION']
personnelcompensationbQ217 = personnelcompensationQ217.loc[personnelcompensationQ217['AMOUNT'] >0]
payee2017Q2 = personnelcompensationbQ217.loc[:, ['OFFICE','PAYEE']].drop_duplicates(subset=['PAYEE'])
payee2017Q2['Period'] = '2017 Q2'
staffcountQ217 = personnelcompensationbQ217['PURPOSE'].value_counts().rename_axis('Position').reset_index(name='count')
staffcompQ217 = personnelcompensationbQ217.groupby(['PURPOSE'])['AMOUNT'].agg('sum').rename_axis('Position').reset_index(name='total compensation')
staffsalary2017Q2 = pd.merge(left=staffcountQ217, right=staffcompQ217, on='Position', how='inner')
staffsalary2017Q2['avg salary'] = staffsalary2017Q2['total compensation'] / staffsalary2017Q2['count']
staffsalary2017Q2['Period'] = '2017 Q2'
#staffsalary2017Q3['Position'] = staffsalary2017Q3['Position'].astype(str)
staffsalary2017Q2 = staffsalary2017Q2[~staffsalary2017Q2["Position"].str.contains('TOTALS:')]
staffsalary2017Q2.sort_values(['avg salary'], ascending=False).head(10)
staffsalary2017Q2.loc[(staffsalary2017Q2['avg salary'] == 43125.0)]
staffsalary2017Q4 = staffsalary2017Q4[~staffsalary2017Q4['Position'].str.contains('(OVERTIME)')]
staffsalary2017Q4 = staffsalary2017Q4[~staffsalary2017Q4['Position'].str.contains('(OTHER COMPENSATION)')]
staffsalary2017Q4 = staffsalary2017Q4[~staffsalary2017Q4['Position'].str.contains('(ASST)')]
staffsalary2017Q4.sort_values(['avg salary'], ascending=True).head(15)
payee2017Q2

/var/folders/jr/dnsfm9kj2575clb1_33r_09w0000gn/T/ipykernel_42049/3590972159.py:14: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  staffsalary2017Q4 = staffsalary2017Q4[~staffsalary2017Q4['Position'].str.contains('(OVERTIME)')]
/var/folders/jr/dnsfm9kj2575clb1_33r_09w0000gn/T/ipykernel_42049/3590972159.py:15: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  staffsalary2017Q4 = staffsalary2017Q4[~staffsalary2017Q4['Position'].str.contains('(OTHER COMPENSATION)')]
/var/folders/jr/dnsfm9kj2575clb1_33r_09w0000gn/T/ipykernel_42049/3590972159.py:16: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  staffsalary2017Q4 = staffsalary2017Q4[~staffsalary2017Q4['Position'].str.contains('(ASST)')]

,OFFICE,PAYEE,Period
0,2017 OFFICE OF THE SPEAKER,ALTHOUSE JOSHUA S,2017 Q2
1,2017 OFFICE OF THE SPEAKER,ANDRES DOUGLAS R,2017 Q2
2,2017 OFFICE OF THE SPEAKER,ANDREWS THOMAS S,2017 Q2
3,2017 OFFICE OF THE SPEAKER,ANTELL GEOFFREY,2017 Q2
4,2017 OFFICE OF THE SPEAKER,BENJAMIN WILLIAM C.,2017 Q2
...,...,...,...
105674,FISCAL YEAR 2017 OFFICE OF CONGRESSIONAL ETHICS,BREWINGTON KELLY D,2017 Q2
105675,FISCAL YEAR 2017 OFFICE OF CONGRESSIONAL ETHICS,CHO HEEJUNG,2017 Q2
105676,FISCAL YEAR 2017 OFFICE OF CONGRESSIONAL ETHICS,EISNER HELEN P,2017 Q2
105677,FISCAL YEAR 2017 OFFICE OF CONGRESSIONAL ETHICS,SOLIS PAUL J,2017 Q2
105680,FISCAL YEAR 2017 OFFICE OF CONGRESSIONAL ETHICS,BROWN JEFFREY L,2017 Q2

In [ ]:
def positioncounts(df):
    """count total jobs each year"""
    
    return df['count'].sum()

In [ ]:
print(positioncounts(staffsalary2016Q1))
print(positioncounts(staffsalary2016Q2))
print(positioncounts(staffsalary2016Q3))
print(positioncounts(staffsalary2016Q4))
print(positioncounts(staffsalary2017Q1))
print(positioncounts(staffsalary2017Q2))
print(positioncounts(staffsalary2017Q3))
print(positioncounts(staffsalary2017Q4))

19239
11168
11070
10829
20992
11879
11301
11052

In [ ]:
def internpositioncounts(df):
    "Count temporary/permanent position"
    return df.loc[df['AMOUNT'] > 4000].shape

In [ ]:
print(internpositioncounts(personnelcompensationb16Q1))
print(internpositioncounts(personnelcompensationb16Q2))
print(internpositioncounts(personnelcompensationb16Q3))
print(internpositioncounts(personnelcompensationb16Q4))
print(internpositioncounts(personnelcompensationb17Q1))
print(internpositioncounts(personnelcompensationbQ217))
print(internpositioncounts(personnelcompensationbQ317))
print(internpositioncounts(personnelcompensationbQ417))

(9714, 15)
(9652, 15)
(9685, 15)
(10158, 15)
(9916, 15)
(10226, 14)
(10314, 15)
(10792, 15)

In [ ]:
allstaffsalary = pd.concat([staffsalary2016Q1,staffsalary2016Q2,staffsalary2016Q3,staffsalary2016Q4,staffsalary2017Q1,staffsalary2017Q2, staffsalary2017Q3,staffsalary2017Q4])
def top10(df):
    """Output top 10 highest paid jobs."""
    
    return df.loc[df['avg salary'] == 43125.000]
    #return df.sort_values(['avg salary'], ascending=False).head(15)

In [ ]:
joboveryear = allstaffsalary.groupby('Period').apply(top10)
pd.set_option('display.max_rows', joboveryear.shape[0]+1)
joboveryear['Position'].value_counts()
#joboveryear

CLERK OF THE HOUSE                8
HOUSE CHAPLAIN                    8
SERGEANT AT ARMS                  8
LAW REVISION COUNSEL              8
INSPECTOR GENERAL                 7
DIRECTOR OF HOUSE OPERATIONS      6
CHIEF OF STAFF/GENERAL COUNSEL    6
GENERAL COUNSEL/OVERSIGHT         6
CLERK AND STAFF DIRECTOR          5
DIRECTOR OF WORKFORCE POLICY      4
PARLIAMENTARIAN                   4
CHIEF ADV ON COMMUNICATIONS       3
STAFF DIRECTOR/CHIEF COUNSEL      3
FLOOR DIRECTOR - STATUTORY        3
COUNSELOR TO THE SPEAKER          3
STAFF DIRECTOR - MAJORITY         2
CHF FINANCIAL INSTITUTION COUN    1
ASST FLOOR CHIEF                  1
Name: Position, dtype: int64

In [ ]:
#calculate retention rate 2016
allstaff2016 = pd.concat([payee2016Q1,payee2016Q2,payee2016Q3,payee2016Q4])
retention2016 = allstaff2016.Period.groupby(allstaff2016.PAYEE).value_counts().unstack().fillna(0)
retention2016[retention2016 > 1] = 1
retention2016['total'] = retention2016[list(retention2016.columns)].sum(axis=1)
retention2016['retention rate'] = retention2016['total'] * 100 / 4
retention2016['retention rate'].describe()

count    20865.000000
mean        47.387970
std         24.088437
min         25.000000
25%         25.000000
50%         25.000000
75%         75.000000
max        100.000000
Name: retention rate, dtype: float64

In [ ]:
#calculate retention rate 2017
allstaff2017 = pd.concat([payee2017Q1,payee2017Q2,payee2017Q3,payee2017Q4])

retention2017 = allstaff2017.Period.groupby(allstaff2017.PAYEE).value_counts().unstack().fillna(0)
retention2017[retention2017 > 1] = 1
retention2017['total'] = retention2017[list(retention2017.columns)].sum(axis=1)
retention2017['retention rate'] = retention2017['total'] * 100 / 4
retention2017['retention rate'].describe()

count    12511.000000
mean        80.698985
std         28.512149
min         25.000000
25%         50.000000
50%        100.000000
75%        100.000000
max        100.000000
Name: retention rate, dtype: float64

In [ ]:
#calculate retention rate 2016-2017
allstaff = pd.concat([payee2016Q1,payee2016Q2,payee2016Q3,payee2016Q4,payee2017Q1,payee2017Q2,payee2017Q3,payee2017Q4])
retention = allstaff.Period.groupby(allstaff.PAYEE).value_counts().unstack().fillna(0)
retention[retention > 1] = 1
retention['total'] = retention[list(retention.columns)].sum(axis=1)
retention['retention rate'] = retention['total'] * 100 / 8
retention['retention rate'].describe()

count    24257.000000
mean        41.191718
std         16.368012
min         12.500000
25%         37.500000
50%         37.500000
75%         62.500000
max        100.000000
Name: retention rate, dtype: float64